site_name: NHS LFPSE Taxonomy - DRAFT
site_description: Details for the NHS LFPSE taaxonomy
site_author: Mark Cooper
copyright: Copyright &copy; 2023
theme:
  name: material
  icon:
    logo: post_add
  custom_dir: overrides
  palette:
    primary: teal
  features:
    - navigation.indexes

nav:


plugins:
  - search
  - enumerate-headings:
      toc_depth: 3
      strict: true
  - print-site:
      add_to_navigation: false
      print_page_title: 'NHS LFPSE Taxonomy - DRAFT'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: false
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition  
  - def_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - tables
